name: Deploy ASP.NET Project
on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    # Hier definierst du die Liste deiner Server
    strategy:
      matrix:
        target_server: [iis1-server, iis1-server] 
    
    # GitHub startet jetzt f√ºr jeden Eintrag in der Liste einen eigenen Job
    runs-on: ${{ matrix.target_server }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Publish Projekt
        run: dotnet publish -c Release -o ./publish_output

      - name: Copy to Webroot
        shell: powershell
        run: |
          robocopy ./publish_output "C:\Users\Administrator\Desktop\prod_Files" /MIR
          if ($lastexitcode -le 3) { exit 0 } else { exit $lastexitcode }
