name: Deploy ASP.NET to [Windows - IIS]

on:
  push:
    branches: [ main ]

jobs:

  deploy:
    name: Build and Deploy on Windows Servers

    strategy:
      matrix:
        target_server:
          - iis1-server
          - iis2-server

    runs-on:
      - self-hosted
      - ${{ matrix.target_server }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Publish Project
        run: dotnet publish -c Release -o publish_output

      - name: Deploy to IIS
        shell: powershell
        run: |
          Import-Module WebAdministration

          # AppPool stoppen
          Stop-WebAppPool -Name "DefaultAppPool"

          # Kurz warten
          Start-Sleep -Seconds 5

          # Dateien kopieren
          robocopy publish_output "C:\inetpub\wwwroot\prod_Files" /MIR
          if ($lastexitcode -gt 3) { exit $lastexitcode }

          # AppPool wieder starten
          Start-WebAppPool -Name "DefaultAppPool"

