name: Deploy ASP.NET Project

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Build on Ubuntu
    runs-on: [self-hosted, carry1_host]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Publish Project
        run: dotnet publish -c Release -o publish_output

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: aspnet-publish
          path: publish_output

  deploy:
    name: Deploy to IIS
    needs: build

    strategy:
      matrix:
        target_server: [iis1-server, iis2-server]

    runs-on: [self-hosted, ${{ matrix.target_server }}]

    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: aspnet-publish
          path: publish_output

      - name: Deploy to IIS Webroot
        shell: powershell
        run: |
          robocopy publish_output "C:\inetpub\wwwroot\prod_Files" /MIR
          if ($lastexitcode -le 3) { exit 0 } else { exit $lastexitcode }
